CREATE TABLE ACCOUNTS
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME   VARCHAR(250) NOT NULL,
    NAME        VARCHAR(250) NULL,
    EMAIL       VARCHAR(250) NOT NULL,
    PASSWORD    VARCHAR(250) NOT NULL,
    IS_DISABLED BOOLEAN      NOT NULL DEFAULT FALSE,
    ROLE        VARCHAR(50)  NOT NULL

);

CREATE
UNIQUE INDEX "USER_NAME_INDEX"
    ON  ACCOUNTS ( USER_NAME );

CREATE TABLE TRANSACTIONS
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID  BIGINT NOT NULL,
    AMOUNT      DOUBLE       NOT NULL,
    TIMESTAMP   TIMESTAMP         NOT NULL,
    DETAILS    VARCHAR(250)  NULL,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID)
);

CREATE INDEX "TIMESTAMP_INDEX"
    ON  TRANSACTIONS ( TIMESTAMP );